### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CuteWolf17** [SwitchbladeBot/switchblade#1089]
app[web.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'findOne' of undefined
at ConfigurationModule.retrieve (/app/src/modules/ConfigurationModule.js:21:25)
at Switchblade.onMessage (/app/src/listeners/MainListener.js:101:67)
at Switchblade.emit (events.js:182:13)
at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
at WebSocket.emit (events.js:182:13)
at Receiver._receiver.onmessage (/app/node_modules/ws/lib/websocket.js:137:47)
at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:397:14)
at Receiver.getData (/app/node_modules/ws/lib/receiver.js:347:12)
at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:143:16)
at Receiver.add (/app/node_modules/ws/lib/receiver.js:117:10)
at TLSSocket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at TLSSocket.Readable.push (_stream_readable.js:219:10)
at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by pedrofracassi** [comment]
Please give [this](https://github.com/SwitchbladeBot/switchblade#self-hosting) a read.
