### ISSUE TITLE
Doesn't run without a database/lavalink connection

### ISSUE THREAD

**Issue by JiMMYBOOi** [SwitchbladeBot/switchblade#175]
I tried running it but it gives me these errors.
```[ErrorLog] Error: URL malformed, cannot be parsed
    at module.exports (/home/pi/switchblade/node_modules/mongodb/lib/url_parser.js:17:21)
    at connect (/home/pi/switchblade/node_modules/mongodb/lib/mongo_client.js:880:3)
    at connectOp (/home/pi/switchblade/node_modules/mongodb/lib/mongo_client.js:270:3)
    at executeOperation (/home/pi/switchblade/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/home/pi/switchblade/node_modules/mongodb/lib/mongo_client.js:261:10)
    at Promise (/home/pi/switchblade/node_modules/mongoose/lib/connection.js:436:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/home/pi/switchblade/node_modules/mongoose/lib/connection.js:433:19)
    at Mongoose.connect (/home/pi/switchblade/node_modules/mongoose/lib/index.js:208:15)
    at MongoDB.connect (/home/pi/switchblade/src/database/mongo/MongoDB.js:15:21)
    at Switchblade.initializeDatabase (/home/pi/switchblade/src/Switchblade.js:207:19)
    at new Switchblade (/home/pi/switchblade/src/Switchblade.js:23:10)
    at Object.<anonymous> (/home/pi/switchblade/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
(node:489) ExperimentalWarning: The http2 module is an experimental API.
[Discord] Logged in successfully!
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND undefined undefined:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
Emitted 'error' event at:
    at LavalinkNode.node.on.error (/home/pi/switchblade/node_modules/discord.js-lavalink/src/lib/PlayerManager.js:69:47)
    at LavalinkNode.emit (events.js:182:13)
    at LavalinkNode._error (/home/pi/switchblade/node_modules/discord.js-lavalink/src/lib/LavalinkNode.js:222:14)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (/home/pi/switchblade/node_modules/discord.js-lavalink/node_modules/ws/lib/websocket.js:535:10)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Doges** [comment]
Which exactly node version are you using?

**Comment by JiMMYBOOi** [comment]
I'm running 10.5.0
```pi@raspberrypi:~ $ nodejs --version
v10.5.0```

**Comment by davipatury** [comment]
The problem isn't your node version, it's the MongoDB connection

**Comment by bolsomito** [comment]
@JiMMYBOOi you're sure that you have all the [environment variables](https://github.com/SwitchbladeBot/switchblade/wiki/Environment-Variables) defined in your .env, right?

**Comment by bolsomito** [comment]
(continuing) because I'm running Switchblade on node v10.5.0 too and it's working as intended

**Comment by pedrofracassi** [comment]
The errors you're getting are related to some [required environment variables](https://github.com/SwitchbladeBot/switchblade/wiki/Environment-Variables) that are missing.

**Comment by JiMMYBOOi** [comment]
how do I find the MONGODB_URI ?

**Comment by Doges** [comment]
You need to create a MONGODB database first, here an example of URI:
**``mongodb://username:password@host1:port``**

**Comment by JiMMYBOOi** [comment]
I added a mongodb uri now I'm getting this error.
```
[ErrorLog] { MongoError: Server at 127.0.0.1:27017 reports wire version 0, but this version of Node.js Driver requires at least 2 (MongoDB2.6).
    at /home/pi/switchblade/node_modules/mongodb-core/lib/topologies/server.js:379:39
    at /home/pi/switchblade/node_modules/mongodb-core/lib/connection/pool.js:544:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  name: 'MongoError',
  message:
   'Server at 127.0.0.1:27017 reports wire version 0, but this version of Node.js Driver requires at least 2 (MongoDB2.6).' }
```

**Comment by bolsomito** [comment]
[Upgrade MongoDB](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)

**Comment by JiMMYBOOi** [comment]
it says I'm on wire version 0 ?
``` { MongoError: Server at 127.0.0.1:27017 reports wire version 0,```

**Comment by bolsomito** [comment]
you need to upgrade your MongoDB from 2.6 to 3.6
