### ISSUE TITLE
Error while trying to self-host

### ISSUE THREAD

**Issue by MrGaabriel** [SwitchbladeBot/switchblade#339]
I was trying to self-host Switchblade and I got this error...

```
(node:744) UnhandledPromiseRejectionWarning: Error: invalid signature: 0x6d783f3c
    at /root/Switchblade/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)```

**Comment by pedrofracassi** [comment]
We don't support self-hosting.
