### ISSUE TITLE
s!uigradient not working

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#660]
When running `s!uigradient` on production, the bot types forever and throws this error to the console

```
(node:9) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
  embed.url: Not a well formed URL.
      at item.request.gen.end (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
      at then (/app/node_modules/discord.js/node_modules/snekfetch/src/index.js:215:21)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 209)
```

**Comment by metehus** [comment]
fuck

**Comment by Doges** [comment]
Cannot Reproduce:
![](https://i.imgur.com/yQPXmUT.png)

**Comment by metehus** [comment]
some names have ' and + and it may glitch the discord embed url
