### ISSUE TITLE
Blacklist Command throws an error

### ISSUE THREAD

**Issue by Flame-0** [SwitchbladeBot/switchblade#816]
**Bug Description**
Executing blacklist command will throw an error

**How to Reproduce**
1. Do `s!blacklist <user: @user> <reason: reason>`

**Expected Behavior**
```
TypeError: Cannot read property 'developers' of undefined
    at BlacklistCommand.run (src\commands\developers\blacklist.js:20:24)
    at BlacklistCommand._run (src\structures\command\Command.js:69:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dpaiv0** [comment]
CR.

**Comment by Doges** [comment]
thats actually p0
